<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE capacites [
    <!ELEMENT capacites (capacite+)>
    <!ELEMENT capacite (nom, type?, puissance?, precision?, pp, boostCrit?, nbFrappe?, tourAvant?, tourApres?, pokemons?, effets?)>
    <!ATTLIST capacite id CDATA #REQUIRED> 
    <!ELEMENT nom (#PCDATA)>
    <!ELEMENT type (#PCDATA)>
    <!ELEMENT puissance (#PCDATA)>
    <!ELEMENT precision (#PCDATA)>
    <!ELEMENT pp (#PCDATA)>
    <!ELEMENT boostCrit EMPTY>
    <!ELEMENT nbFrappe EMPTY>
    <!ATTLIST nbFrappe min CDATA #REQUIRED>
    <!ATTLIST nbFrappe max CDATA #REQUIRED>
    <!ELEMENT tourAvant EMPTY>
    <!ELEMENT tourApres EMPTY>
    <!ELEMENT pokemons (#PCDATA)>
    <!ELEMENT effets (effet+)>
    <!ELEMENT effet (cible, (statut | statistique | special))>
    <!ATTLIST effet chance CDATA #IMPLIED>
    <!ELEMENT cible (#PCDATA)>
    <!ELEMENT statut (#PCDATA)>
    <!ELEMENT statistique (#PCDATA)>
    <!ATTLIST statistique modifier CDATA #REQUIRED>
    <!ELEMENT special (#PCDATA)>
    <!ATTLIST special modifier CDATA #IMPLIED>
]>

<capacites>
    <!-- Liste des attaques obtenues à partir de https://www.pokemon-france.com/jeux/gen1/bleu_rouge/attaques ]-->
    
    <!--
        <capacite id="">
            <nom></nom>
            <type></type>
            <puissance></puissance>
            <precision></precision>
            <pp></pp>
            <nbFrappe min="" max=""/>
            <tourAvant/>
            <tourApres/>
            <pokemons></pokemons>
            <effets>
                <effet chance="">
                    <cible></cible>
                    <statut></statut>
                </effet>
                <effet chance="">
                    <cible></cible>
                    <statistique modifier=""></statistique>
                </effet>
                <effet chance="">
                    <cible></cible>
                    <special modifier=""></special>
                </effet>
            </effets>
        </capacite>
    -->
    
    <capacite id="0">
        <nom>Lutte</nom>
        <puissance>50</puissance>
        <precision>100</precision>
        <pp>1</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <special modifier="0.5">CONTRECOUP</special>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="1">
        <nom>Abîme</nom>
        <type>Sol</type>
        <precision>30</precision>
        <pp>5</pp>
        <effets>
            <effet>
                <cible>Adversaire</cible>
                <statistique modifier="-1.">Vie</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="2">
        <nom>Acidarmure</nom>
        <type>Poison</type>
        <pp>40</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <statistique modifier="3">Def</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="3">
        <nom>Acide</nom>
        <type>Poison</type>
        <puissance>40</puissance>
        <pp>30</pp>
        <effets>
            <effet chance="33">
                <cible>Adversaire</cible>
                <statistique modifier="-1">Def</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="4">
        <nom>Adaptation</nom>
        <type>Normal</type>
        <pp>30</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <special>Copie_Type</special>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="5">
        <nom>Affûtage</nom>
        <type>Normal</type>
        <pp>30</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <statistique modifier="1">Atq</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="6">
        <nom>Amnésie</nom>
        <type>Psy</type>
        <pp>20</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <statistique modifier="2">DefSpe</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="7">
        <nom>Armure</nom>
        <type>Normal</type>
        <pp>30</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <statistique modifier="1">Def</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="8">
        <nom>Balayage</nom>
        <type>Combat</type>
        <puissance>50</puissance>
        <precision>90</precision>
        <pp>20</pp>
        <effets>
            <effet chance="33">
                <cible>Adversaire</cible>
                <special>Peur</special>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="9">
        <nom>Bec Vrille</nom>
        <type>Vol</type>
        <puissance>80</puissance>
        <pp>20</pp>
    </capacite>
    
    <capacite id="10">
        <nom>Bélier</nom>
        <type>Normal</type>
        <puissance>90</puissance>
        <precision>85</precision>
        <pp>20</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <special modifier="0.25">CONTRECOUP</special>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="11">
        <nom>Berceuse</nom>
        <type>Normal</type>
        <precision>55</precision>
        <pp>15</pp>
        <effets>
            <effet>
                <cible>Adversaire</cible>
                <statut>Sommeil</statut>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="12">
        <nom>Blizzard</nom>
        <type>Glace</type>
        <puissance>120</puissance>
        <precision>90</precision>
        <pp>5</pp>
        <effets>
            <effet chance="10">
                <cible>Adversaire</cible>
                <statut>Gel</statut>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="13">
        <nom>Bomb'oeuf</nom>
        <type>Normal</type>
        <puissance>100</puissance>
        <precision>75</precision>
        <pp>10</pp>
    </capacite>
    
    <capacite id="14">
        <nom>Bouclier</nom>
        <type>Psy</type>
        <pp>30</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <statistique modifier="2">Def</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="15">
        <nom>Boul'armure</nom>
        <type>Normal</type>
        <pp>40</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <statistique modifier="1">Def</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="16">
        <nom>Brouillard</nom>
        <type>Normal</type>
        <pp>20</pp>
        <effets>
            <effet>
                <cible>Adversaire</cible>
                <statistique modifier="-1">Precision</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="17">
        <nom>Brume</nom>
        <type>Glace</type>
        <pp>30</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <special>NO_STATUS_CHANGE</special>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="18">
        <nom>Buée Noire</nom>
        <type>Glace</type>
        <pp>30</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <statut>Neutre</statut>
            </effet>
            <effet>
                <cible>Adversaire</cible>
                <statut>Neutre</statut>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="19">
        <nom>Bulles D'O</nom>
        <type>Eau</type>
        <puissance>65</puissance>
        <pp>20</pp>
        <effets>
            <effet chance="33">
                <cible>Adversaire</cible>
                <statistique modifier="-1">Vitesse</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="20">
        <nom>Cage-Eclair</nom>
        <type>Electrik</type>
        <pp>20</pp>
        <effets>
            <effet>
                <cible>Adversaire</cible>
                <statut>Paralysie</statut>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="21">
        <nom>Cascade</nom>
        <type>Eau</type>
        <puissance>80</puissance>
        <pp>15</pp>
    </capacite>
    
    <capacite id="22">
        <nom>Charge</nom>
        <type>Normal</type>
        <puissance>35</puissance>
        <precision>95</precision>
        <pp>35</pp>
    </capacite>
    
    <capacite id="23">
        <nom>Choc Mental</nom>
        <type>Psy</type>
        <puissance>50</puissance>
        <pp>25</pp>
        <effets>
            <effet chance="10">
                <cible>Adversaire</cible>
                <statut>Confusion</statut>
            </effet>
        </effets>
    </capacite>
    
    <!--
        <capacite id="24">
            <nom>Claquoir</nom>
            <type>Eau</type>
            <puissance>35</puissance>
            <precision>75</precision>
            <pp>10</pp>
            <effets>
                <effet>
                    <cible>Adversaire</cible>
                    <special>Claquoir</special>
                </effet>
            </effets>
        </capacite> 
    -->
    
    <capacite id="25">
        <nom>Clonage</nom>
        <type>Normal</type>
        <pp>10</pp>
        <effets>
            <effet>
                <cible>lanceur</cible>
                <special>Clonage</special>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="26">
        <nom>Combo-griffe</nom>
        <type>Normal</type>
        <puissance>18</puissance>
        <precision>80</precision>
        <pp>15</pp>
        <nbFrappe min="2" max="5"/>
    </capacite>
    
    <capacite id="27">
        <nom>Constriction</nom>
        <type>Normal</type>
        <puissance>10</puissance>
        <pp>35</pp>
        <effets>
            <effet chance="33">
                <cible>Adversaire</cible>
                <statistique modifier="-1">Vitesse</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="28">
        <nom>Copie</nom>
        <type>Normal</type>
        <pp>10</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <special>COPIE_CAPACITE</special>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="29">
        <nom>Coud'boule</nom>
        <type>Normal</type>
        <puissance>70</puissance>
        <pp>15</pp>
        <effets>
            <effet chance="33">
                <cible>Adversaire</cible>
                <special>Peur</special>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="30">
        <nom>Coud'krâne</nom>
        <type>Normal</type>
        <puissance>100</puissance>
        <pp>15</pp>
        <tourAvant/>
    </capacite>
    
    <capacite id="31">
        <nom>Coupe</nom>
        <type>Normal</type>
        <puissance>50</puissance>
        <precision>95</precision>
        <pp>30</pp>
    </capacite>
    
    <capacite id="32">
        <nom>Coupe-vent</nom>
        <type>Vol</type>
        <puissance>80</puissance>
        <precision>75</precision>
        <pp>30</pp>
        <tourAvant/>
    </capacite>
    
    <capacite id="33">
        <nom>Croc de Mort</nom>
        <type>Normal</type>
        <puissance>80</puissance>
        <precision>70</precision>
        <pp>15</pp>
        <effets>
            <effet chance="10">
                <cible>Adversaire</cible>
                <special>Peur</special>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="34">
        <nom>Croc Fatal</nom>
        <type>Normal</type>
        <precision>90</precision>
        <pp>10</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <statistique modifier="-0.5">Vie</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="35">
        <nom>Croissance</nom>
        <type>Normal</type>
        <pp>40</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <statistique modifier="1">Atq</statistique>
            </effet>
            <effet>
                <cible>Lanceur</cible>
                <statistique modifier="1">AtqSpe</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="36">
        <nom>Cru-aile</nom>
        <type>Vol</type>
        <puissance>35</puissance>
        <pp>35</pp>
    </capacite>
    
    <capacite id="37">
        <nom>Damoclès</nom>
        <type>Normal</type>
        <puissance>100</puissance>
        <pp>15</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <special modifier="0.25">CONTRECOUP</special>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="38">
        <nom>Danseflamme</nom>
        <type>Feu</type>
        <puissance>15</puissance>
        <precision>70</precision>
        <pp>15</pp>
        <nbFrappe min="2" max="5"/>
    </capacite>
    
    <capacite id="39">
        <nom>Danse-Fleur</nom>
        <type>Plante</type>
        <puissance>120</puissance>
        <precision>75</precision>
        <pp>10</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <statut>CONFUSION</statut>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="40">
        <nom>Danse-Lames</nom>
        <type>Normal</type>
        <pp>20</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <statistique modifier="2">Atq</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="41">
        <nom>Dard-Nuée</nom>
        <type>Insecte</type>
        <puissance>14</puissance>
        <precision>85</precision>
        <pp>20</pp>
        <nbFrappe min="2" max="5"/>
    </capacite>
    
    <capacite id="42">
        <nom>Dard-Venin</nom>
        <type>Poison</type>
        <puissance>15</puissance>
        <precision>100</precision>
        <pp>35</pp>
        <effets>
            <effet chance="20">
                <cible>Adversaire</cible>
                <statut>Empoisonnement</statut>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="43">
        <nom>Déflagration</nom>
        <type>Feu</type>
        <puissance>120</puissance>
        <precision>85</precision>
        <pp>5</pp>
        <effets>
            <effet chance="33">
                <cible>Adversaire</cible>
                <statut>Brulure</statut>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="44">
        <nom>Destruction</nom>
        <type>Normal</type>
        <puissance>260</puissance>
        <pp>5</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <statistique modifier="-1.0">Vie</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="45">
        <nom>Détritus</nom>
        <type>Poison</type>
        <puissance>65</puissance>
        <pp>20</pp>
        <effets>
            <effet chance="50">
                <cible>Adversaire</cible>
                <statut>Empoisonnement</statut>
            </effet>
        </effets>
    </capacite>
    
    <!--<capacite id="46">
        <nom>Dévorêve</nom>
        <type>Psy</type>
        <puissance>100</puissance>
        <pp>15</pp>
    </capacite>-->
    
    <capacite id="47">
        <nom>Double-Dard</nom>
        <type>Insecte</type>
        <puissance>25</puissance>
        <pp>20</pp>
        <nbFrappe min="2" max="2"/>
        <effets>
            <effet chance="36">
                <cible>Adversaire</cible>
                <statut>Empoisonnement</statut>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="48">
        <nom>Double-pied</nom>
        <type>Combat</type>
        <puissance>30</puissance>
        <pp>30</pp>
        <nbFrappe min="2" max="2"/>
    </capacite>
    
    <capacite id="49">
        <nom>Draco-rage</nom>
        <type>Dragon</type>
        <pp>10</pp>
        <effets>
            <effet>
                <cible>Adversaire</cible>
                <statistique modifier="-40">Vie</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="50">
        <nom>Eboulement</nom>
        <type>Roche</type>
        <puissance>80</puissance>
        <precision>90</precision>
        <pp>10</pp>
    </capacite>
    
    <capacite id="51">
        <nom>Eclair</nom>
        <type>Electrik</type>
        <puissance>40</puissance>
        <pp>30</pp>
        <pokemons>25</pokemons>
        <effets>
            <effet chance="10">
                <cible>Adversaire</cible>
                <statut>Paralysie</statut>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="52">
        <nom>E-coque</nom>
        <type>Normal</type>
        <pp>10</pp>
        <effets>
            <effet>
                <cible>Lanceur</cible>
                <statistique modifier="0.5">Vie</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="53">
        <nom>Ecrasement</nom>
        <type>Normal</type>
        <puissance>65</puissance>
        <pp>20</pp>
        <effets>
            <effet chance="33">
                <cible>Adversaire</cible>
                <special>Peur</special>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="54">
        <nom>Ecras'face</nom>
        <type>Normal</type>
        <puissance>40</puissance>
        <pp>35</pp>
    </capacite>
    
    <capacite id="55">
        <nom>Ecume</nom>
        <type>Eau</type>
        <puissance>20</puissance>
        <pp>30</pp>
        <effets>
            <effet chance="33">
                <cible>Adversaire</cible>
                <statistique modifier="-1">Vitesse</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="56">
        <nom>Empal'korne</nom>
        <type>Normal</type>
        <precision>30</precision>
        <pp>5</pp>
        <effets>
            <effet>
                <cible>Adversaire</cible>
                <statistique modifier="-1.0">Vie</statistique>
            </effet>
        </effets>
    </capacite>
    
    <capacite id="57">
        <nom>Entrave</nom>
        <type>Normal</type>
        <precision>55</precision>
        <pp>20</pp>
        <effets>
            <effet>
                <cible>Adversaire</cible>
                <special>Entrave</special>
            </effet>
        </effets>
    </capacite>
    
</capacites>
